apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-values
  labels:
    app.kubernetes.io/name: lua-python-cache-demo
data:
  engine: {{ .Values.engine | quote }}
  message: {{ .Values.message | quote }}
  replicaCount: {{ .Values.replicaCount | quote }}
